version: 2
jobs:
  build:
    working_directory: ~/test_folder
    docker:
      - image: microsoft/windowsservercore
      #- image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: run dir
          command: dir


