version: 2
jobs:
  build:
    working_directory: ~/test_folder
    docker:
      - image: azuresdk/azure-powershell-core
     # - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: run dir
          command: get-date


